name: Build & push to Docker Hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        env: 
          SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
          
      - name: Print SHORT_SHA
        run: |
          echo $SHORT_SHA

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: janwer/sectools
          tags: latest, $SHORT_SHA
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
